export interface UserCardInterface{
    height?: number,
    width?: number,
    borderRadius?: number,
    backgroundColor?: string,
    name?: string,
    textColor?: string,
    fontFamily?: string,
    nameFontSize?: number,
    locationFontSize?: number,
    buttonWidth?: number,
    buttonHeight?: number,
    buttonTitle?: string,
    buttonColor?: string,
    buttonBorderColor?: string,
    buttonBorderWidth?: number,
    buttonFontSize?: number,
    buttonTextColor?: string,
    locationText?: string,
    eventText?: string,
    imageUri?: string,
    imgWidth?: number,
    imgHight?: number,
    imgBorderRadius?: number,
    numberOfStars?: number,
    startColor?: string,
    starSize?: number,
    
}
