export const Colors = {
    "backgroundColor": "#000000",
    "borderColor": "#F5F5F5",
    "textColor": "#DDDDDD",
    "iconColor": "#EEEDED",
    "errorColor": "#F8F6F4",
    "activeOutlineColor": "#ffffff",
    "outlineColor": "#F8F6F4",
    "disabledBackgroundColor": "#ffffff",
    "disabledBorderColor": "#000000",
    "disabledTextColor": "#000000",
    "disabledIconColor": "#EEEDED",
    "disabledErrorColor": "#F8F6F4",
    "disabledActiveOutlineColor": "#000000",
    "disabledOutlineColor": "#000000",
    "placeholderTextColor": "#fff",
}
