export interface PrimaryButtonInterface {
    title?: string,
    buttonColor?: string,
    height?: number,
    width?: number,
    fontSize?: number,
    color?: string,
    borderColor?:string,
    borderWidth?:number,
    borderRadius?:number,
    disabled?:boolean,
    marginTopLabel?:number,
    marginBottomLabel?:number,
    marginLeftLabel?:number,
    marginRightLabel?:number,
    marginTopButton?:number,
    marginBottomButton?:number,
    marginLeftButton?:number,
    marginRightButton?:number,
    disabledColor?: string,
    disabledButtonColor?: string,
    disabledBorderColor?:string,
}