export interface PrimarySecondaryButtonInterface {
    title?: string,
    buttonColor?: string,
    height?: number,
    width?: number,
    fontSize?: number,
    color?: string,
    borderColor?:string,
    borderWidth?:number,
    borderRadius?:number,
    disabled?:boolean,
    marginTop?:number,
    marginBottom?:number,
    marginLeft?:number,
    marginRight?:number,
}