export interface SearchBarInterface {
    placeHolder?: string,
    backgroundColor?: string,
    mode?: string,
    width?: number,
    activeOutlineColor?: string,
    outlineColor?: string,
    textColor?: string,
    borderRadius?: number,
    error?: boolean,
    errorMessage?: string,
    fontSize?: number,
    iconColor?: string,
    disabled?: boolean,
    inProgress?: boolean,
    errorColor?: string,
    iconSize?:number,
    marginTop?:number,
    marginBottom?:number,
    marginLeft?:number,
    marginRight?:number,
    height?:number,
}