export interface DatePickerInterface {
    placeHolder?: string,
    backgroundColor?: string,
    mode?: string,
    width?: number,
    activeOutlineColor?: string,
    outlineColor?: string,
    textColor?: string,
    borderRadius?: number,
    error?: boolean,
    errorMessage?: string,
    fontSize?: number,
    iconColor?: string,
    height?: number,
    errorColor?: string,
    iconSize?: number,
    placeholderTextColor?: string,
}