export interface DatePickerInterface{
    placeHolder?: string,
    backgroundColor?: string,
    mode?: string,
    width?: number,
    activeOutlineColor?: string,
    outlineColor?: string,
    textColor?: string,
    borderRadius?: number,
    error?: boolean,
    errorMessage?: string,
    fontSize?: number,
    iconColor ?: string,
    disabled?:boolean,
    height?:number,
}