export interface InputFieldIconInterface {
    label?:string,
    placeHolder?: string,
    backgroundColor?: string,
    mode?: string,
    width?: number,
    activeOutlineColor?: string,
    outlineColor?: string,
    textColor?: string,
    borderRadius?: number,
    error?: boolean,
    errorMessage?: string,
    fontSize?: number,
    iconColor ?: string,
    disabled?:boolean,
    placeholderTextColor?:string,
    iconSize?:number,
    errorColor?:string,
    marginTop?:number,
    marginBottom?:number,
    marginLeft?:number,
    marginRight?:number,
    height?:number,
    featherIconName?:string,
    value?:string,
}