export interface InputTextAreaInterface {
    label?:string,
    placeHolder?: string,
    backgroundColor?:string,
    mode?:string,
    width?:number,
    activeOutlineColor?:string,
    outlineColor?:string,
    textColor?:string,
    borderRadius?:number,
    error ?: boolean,
    errorMessage ?:string,
    fontSize?:number,
    numberOfLines?:number,
    multiline?:boolean,
    errorColor?:string,
    placeholderTextColor?:string,
    marginTop?:number,
    marginBottom?:number,
    marginLeft?:number,
    marginRight?:number,
    value?:string,
    fontFamily?: string,
    infoMessage?:string,
    infoDisplay?:boolean,
    infoColor?:string
}