export interface InputTextAreaInterface {
    placeHolder?: string,
    backgroundColor?:string,
    mode?:string,
    width?:number,
    activeOutlineColor?:string,
    outlineColor?:string,
    textColor?:string,
    borderRadius?:number,
    error ?: boolean,
    errorMessage ?:string,
    fontSize?:number,
    numberOfLines?:number,
    multiline?:boolean,
}