export interface TextInputOutlinedInterface {
    placeHolder?: string,
    backgroundColor?:string,
    mode?:string,
    width?:number,
    activeOutlineColor?:string,
    outlineColor?:string,
    textColor?:string,
    maxLength?:number,
    keyboardType?:string,
    borderRadius?:number,
    error ?: boolean,
    errorMessage ?:string,
    fontSize?:number,
    disabled?:boolean,
    textAlign?:string,
}