export interface TextInputOutlinedInterface {
    label?:string,
    placeHolder?: string,
    backgroundColor?:string,
    mode?:string,
    width?:number,
    activeOutlineColor?:string,
    outlineColor?:string,
    textColor?:string,
    maxLength?:number,
    keyboardType?:string,
    borderRadius?:number,
    error ?: boolean,
    errorMessage ?:string,
    fontSize?:number,
    disabled?:boolean,
    textAlign?:string,
    errorColor?:string,
    placeholderTextColor?:string,
    marginTop?:number,
    marginBottom?:number,
    marginLeft?:number,
    marginRight?:number,
    height?:number,
    value?:string,
    errorFontSize?:number,
    fontFamily?: string,
    infoMessage?:string,
    infoDisplay?:boolean
    infoColor?:string
}